MVCHello/Models/ErrorViewModel.cs
namespace MVCHello.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCHello/Models/Name.cs
namespace MVCHello.Models
{
    public class Name
    {
        public string userName { get; set; }

    }
}

MVCHello/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCHello.Models;
using System.Diagnostics;

namespace MVCHello.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

MVCHello/Controllers/NameController.cs
using Microsoft.AspNetCore.Mvc;
using MVCHello.Models;

namespace MVCHello.Controllers
{
    public class NameController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register(Name name)
        {
            return View(name);
        }
    }
}

MVCHello/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using(Html.BeginForm("Register","Name", FormMethod.Post))
{
    <p>Input your name:</p>
    <p>@Html.TextBox("userName")</p>
    <button type="submit">Submit</button>
}

MVCHello/Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

MVCHello/Views/Name/Register.cshtml
@model Name;
@{
    ViewData["Title"] = "Register";
}

<h1>Hello @Model.userName</h1>

MVCHello/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCHello</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCHello.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCHello</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCHello - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>